// <auto-generated />
using System;
using AracKiralama.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AracKiralama.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240707171222_mig7")]
    partial class mig7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AracKiralama.Models.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AracFotograf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracMarka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AracMusait")
                        .HasColumnType("bit");

                    b.Property<string>("AracPlaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracSanziman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracYakit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracYil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("GunlukFiyat")
                        .HasColumnType("real");

                    b.Property<int?>("KiralamaIslemiId")
                        .HasColumnType("int");

                    b.Property<int?>("MotorHacmi")
                        .HasColumnType("int");

                    b.Property<int?>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("AracKiralama.Models.KiralamaIslemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemZamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("KiralamaBaslangicSaati")
                        .HasColumnType("int");

                    b.Property<DateTime>("KiralamaBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KiralamaBitisSaati")
                        .HasColumnType("int");

                    b.Property<DateTime>("KiralamaBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KiralananGunSayisi")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.Property<int>("SubeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("SehirId");

                    b.HasIndex("SubeId");

                    b.ToTable("KiralamaIslemleri");
                });

            modelBuilder.Entity("AracKiralama.Models.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MusteriAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MusteriAktif")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("MusteriDogTar")
                        .HasColumnType("date");

                    b.Property<string>("MusteriSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTc")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfilFotografi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SonAracId")
                        .HasColumnType("int");

                    b.Property<int?>("SubeId")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EPosta")
                        .IsUnique();

                    b.HasIndex("MusteriTc")
                        .IsUnique();

                    b.HasIndex("SonAracId");

                    b.HasIndex("Telefon")
                        .IsUnique();

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("AracKiralama.Models.Sehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SehirAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("AracKiralama.Models.Sube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SehirId")
                        .HasColumnType("int");

                    b.Property<string>("SubeAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubeAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SehirId");

                    b.ToTable("Subeler");
                });

            modelBuilder.Entity("AracKiralama.Models.KiralamaIslemi", b =>
                {
                    b.HasOne("AracKiralama.Models.Arac", "Arac")
                        .WithMany("KiralamaIslemleri")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AracKiralama.Models.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AracKiralama.Models.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AracKiralama.Models.Sube", "Sube")
                        .WithMany()
                        .HasForeignKey("SubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("Musteri");

                    b.Navigation("Sehir");

                    b.Navigation("Sube");
                });

            modelBuilder.Entity("AracKiralama.Models.Musteri", b =>
                {
                    b.HasOne("AracKiralama.Models.Arac", "SonArac")
                        .WithMany()
                        .HasForeignKey("SonAracId");

                    b.Navigation("SonArac");
                });

            modelBuilder.Entity("AracKiralama.Models.Sube", b =>
                {
                    b.HasOne("AracKiralama.Models.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirId");

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("AracKiralama.Models.Arac", b =>
                {
                    b.Navigation("KiralamaIslemleri");
                });
#pragma warning restore 612, 618
        }
    }
}
